
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fibonnaci_numbers(number)
  first = 1
  second = 1
  fibonnaci = first + second
  total = 0

  until fibonnaci > number
    total += fibonnaci if fibonnaci.even?

    first = second
    second = fibonnaci
    fibonnaci = first + second
  end

  return total
end

puts even_fibonnaci_numbers(4_000_000)